[package]
name = "mithril-end-to-end"
version = "0.4.30"
authors = { workspace = true }
edition = { workspace = true }
documentation = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
default-run = "mithril-end-to-end"

[[bin]]
name = "load-aggregator"
test = false
bench = false

[dependencies]
anyhow = "1.0.86"
async-recursion = "1.1.1"
async-trait = "0.1.82"
clap = { version = "4.5.16", features = ["derive"] }
glob = "0.3.1"
hex = "0.4.3"
indicatif = { version = "0.17.8", features = ["tokio"] }
mithril-common = { path = "../../mithril-common", features = ["full"] }
mithril-doc = { path = "../../internal/mithril-doc" }
reqwest = { version = "0.12.7", features = ["json"] }
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
serde_yaml = "0.9.34"
slog = { version = "2.7.0", features = [
    "max_level_trace",
    "release_max_level_trace",
] }
slog-async = "2.8.0"
slog-scope = "4.4.0"
slog-term = "2.9.1"
thiserror = "1.0.63"
tokio = { version = "1.40.0", features = ["full"] }
tokio-util = { version = "0.7.11", features = ["codec"] }

[features]
default = []
allow_skip_signer_certification = []
