[package]
name = "mithril-signer"
version = "0.2.1"
description = "A Mithril Signer"
authors = { workspace = true }
edition = { workspace = true }
documentation = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
async-trait = "0.1.52"
clap = { version = "4.0", features = ["derive", "env"] }
config = "0.13.1"
hex = "0.4.3"
mithril-common = { path = "../mithril-common" }
rand_chacha = "0.3.1"
rand_core   = "0.6.3"
reqwest = { version = "0.11", features = ["json", "stream"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
slog = { version = "2.7.0", features = ["max_level_trace", "release_max_level_debug"] }
slog-async = "2.7.0"
slog-bunyan = "2.4.0"
slog-scope = "4.4.0"
thiserror = "1.0.31"
tokio = { version = "1.17.0", features = ["full"] }

[dev-dependencies]
httpmock = "0.6.6"
mithril-common = { path = "../mithril-common", features = ["test_only"] }
mockall = "0.11.0"
slog-term = "2.9.0"

[features]
portable = ["mithril-common/portable"]
v2_single_signature_message = ["mithril-common/v2_single_signature_message"]
