[package]
name = "mithril-client-wasm"
version = "0.1.9"
description = "Mithril client WASM"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
categories = ["cryptography"]

[lib]
crate-type = ["cdylib"]

[dependencies]
async-trait = "0.1.77"
mithril-client = { path = "../mithril-client" }
serde = { version = "1.0.196", features = ["derive"] }
serde-wasm-bindgen = "0.6.3"
tokio = { version = "1.35.1", features = ["macros", "rt"] }
tokio-util = "0.7.10"
wasm-bindgen = "0.2.90"
wasm-bindgen-futures = "0.4.40"
web-sys = { version = "0.3.67", features = ["AbortController", "AbortSignal", "BroadcastChannel"] }

[dev-dependencies]
wasm-bindgen-test = "0.3.40"

[features]
# Include nothing by default
default = []

[package.metadata.docs.rs]
all-features = true
# enable unstable features in the documentation
rustdoc-args = ["--cfg", "docsrs"]
