[package]
name = "mithril-persistence"
version = "0.2.25"
description = "Common types, interfaces, and utilities to persist data for Mithril nodes."
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[lib]
crate-type = ["lib", "cdylib", "staticlib"]

[dependencies]
anyhow = "1.0.86"
async-trait = "0.1.82"
chrono = { version = "0.4.38", features = ["serde"] }
hex = "0.4.3"
mithril-common = { path = "../../mithril-common", features = ["fs"] }
semver = "1.0.23"
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
sha2 = "0.10.8"
slog = "2.7.0"
sqlite = { version = "0.36.1", features = ["bundled"] }
thiserror = "1.0.63"
tokio = { version = "1.40.0", features = ["sync"] }

[dev-dependencies]
mithril-common = { path = "../../mithril-common", features = ["test_tools"] }
mockall = "0.13.0"
slog-async = "2.8.0"
slog-scope = "4.4.0"
slog-term = "2.9.1"
tokio = { version = "1.40.0", features = ["macros", "time"] }
