[package]
name = "mithril-aggregator-fake"
version = "0.3.7"
description = "Mithril Fake Aggregator for client testing"
authors = { workspace = true }
documentation = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
anyhow = "1.0.86"
axum = { version = "0.7.5", features = ["tokio", "http1"] }
clap = { version = "4.5.16", features = ["derive"] }
clap_derive = "4.5.13"
futures = "0.3.30"
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
signal-hook = "0.3.17"
signal-hook-tokio = { version = "0.3.1", features = ["futures-v0_3"] }
tokio = { version = "1.40.0", features = ["full"] }
tower-http = { version = "0.5.2", features = ["trace", "cors"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"

[dev-dependencies]
mithril-common = { "path" = "../../mithril-common", features = [
    "test_tools",
    "random",
] }
reqwest = "0.12.7"
warp = "0.3.7"

[build-dependencies]
mithril-build-script = { path = "../../internal/mithril-build-script" }
