[package]
name = "mithril-client-cli"
version = "0.9.11"
description = "A Mithril Client"
authors = { workspace = true }
edition = { workspace = true }
documentation = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[[bin]]
name = "mithril-client"
path = "src/main.rs"

[package.metadata.deb]
depends = "$auto"
section = "utility"
extended-description = """Shows, downloads and verifies certified blockchain artifacts.

Run `mithril-client --help` to display the available options."""
assets = [["../target/release/mithril-client", "usr/bin/", "755"]]

[dependencies]
anyhow = "1.0.86"
async-trait = "0.1.82"
chrono = { version = "0.4.38", features = ["serde"] }
clap = { version = "4.5.16", features = ["derive", "env"] }
cli-table = "0.4.9"
config = "0.14.0"
fs2 = "0.4.3"
futures = "0.3.30"
human_bytes = { version = "0.4.3", features = ["fast"] }
indicatif = { version = "0.17.8", features = ["tokio"] }
mithril-client = { path = "../mithril-client", features = ["fs", "unstable"] }
mithril-doc = { path = "../internal/mithril-doc" }
openssl = { version = "0.10.66", features = ["vendored"], optional = true }
openssl-probe = { version = "0.1.5", optional = true }
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
slog = { version = "2.7.0", features = [
    "max_level_trace",
    "release_max_level_debug",
] }
slog-async = "2.8.0"
slog-bunyan = "2.5.0"
slog-scope = "4.4.0"
slog-term = "2.9.1"
thiserror = "1.0.63"
tokio = { version = "1.40.0", features = ["full"] }

[dev-dependencies]
mithril-common = { path = "../mithril-common", features = ["test_tools"] }

[features]
bundle_openssl = ["dep:openssl", "dep:openssl-probe"]
